const matches = [
  {
    homeTeam: 'Egypt',
    homeFlag: require('../testingTipster/images/Egypt.png'),
    awayTeam: 'Zimbabwe',
    awayFlag: require('../testingTipster/images/Morocco.png'),
    round: 1,
    date: new Date(2019, 6, 21, 22, 0),
  }, {
    homeTeam: 'DR Congo',
    homeFlag: require('../testingTipster/images/DR Congo.png'),
    awayTeam: 'Uganda',
    awayFlag: require('../testingTipster/images/Uganda.png'),
    round: 1,
    date: new Date(2019, 6, 22, 16, 30),
  }, {
    homeTeam: 'Nigeria',
    homeFlag: require('../testingTipster/images/Nigeria.png'),
    awayTeam: 'Burundi',
    awayFlag: require('../testingTipster/images/Burundi.png'),
    round: 1,
    date: new Date(2019, 6, 22, 19, 0),
  }, {
    homeTeam: 'Guinea',
    homeFlag: require('../testingTipster/images/Guinea.png'),
    awayTeam: 'Madagascar',
    awayFlag: require('../testingTipster/images/Madagascar.png'),
    round: 1,
    date: new Date(2019, 6, 22, 22, 0),
  }, {
    homeTeam: 'Senegal',
    homeFlag: require('../testingTipster/images/Senegal.png'),
    awayTeam: 'Tanzania',
    awayFlag: require('../testingTipster/images/Tanzania.png'),
    round: 1,
    date: new Date(2019, 6, 23, 19, 0),
  }, {
    homeTeam: 'Algeria',
    homeFlag: require('../testingTipster/images/Algeria.png'),
    awayTeam: 'Kenya',
    awayFlag: require('../testingTipster/images/Kenya.png'),
    round: 1,
    date: new Date(2019, 6, 23, 22, 0),
  }, {
    homeTeam: 'Morocco',
    homeFlag: require('../testingTipster/images/Morocco.png'),
    awayTeam: 'Namibia',
    awayFlag: require('../testingTipster/images/Namibia.png'),
    round: 1,
    date: new Date(2019, 6, 23, 16, 30),
  }, {
    homeTeam: 'Ivory Coast',
    homeFlag: require('../testingTipster/images/Ivory Coast.png'),
    awayTeam: 'South Africa',
    awayFlag: require('../testingTipster/images/South Africa.png'),
    round: 1,
    date: new Date(2019, 6, 24, 16, 30),
  }, {
    homeTeam: 'Tunisia',
    homeFlag: require('../testingTipster/images/Tunisia.png'),
    awayTeam: 'Angola',
    awayFlag: require('../testingTipster/images/Angola.png'),
    round: 1,
    date: new Date(2019, 6, 24, 19, 0),
  }, {
    homeTeam: 'Mali',
    homeFlag: require('../testingTipster/images/Mali.png'),
    awayTeam: 'Mauritius',
    awayFlag: require('../testingTipster/images/Mauritius.png'),
    round: 1,
    date: new Date(2019, 6, 24, 22, 0),
  }, {
    homeTeam: 'Cameroon',
    homeFlag: require('../testingTipster/images/Cameroon.png'),
    awayTeam: 'Guinea-Bissau',
    awayFlag: require('../testingTipster/images/Guinea-Bissau.png'),
    round: 1,
    date: new Date(2019, 6, 25, 19, 0),
  }, {
    homeTeam: 'Ghana',
    homeFlag: require('../testingTipster/images/Ghana.png'),
    awayTeam: 'Benin',
    awayFlag: require('../testingTipster/images/Benin.png'),
    round: 1,
    date: new Date(2019, 6, 25, 10, 0),
  }, {
    homeTeam: 'Egypt',
    homeFlag: require('../testingTipster/images/Egypt.png'),
    awayTeam: 'DR Congo',
    awayFlag: require('../testingTipster/images/DR Congo.png'),
    round: 2,
    date: new Date(2019, 6, 26, 22, 0),
  }, {
    homeTeam: 'Uganda',
    homeFlag: require('../testingTipster/images/Uganda.png'),
    awayTeam: 'Zimbabwe',
    awayFlag: require('../testingTipster/images/Zimbabwe.png'),
    round: 2,
    date: new Date(2019, 6, 26, 19, 0),
  }, {
    homeTeam: 'Nigeria',
    homeFlag: require('../testingTipster/images/Nigeria.png'),
    awayTeam: 'Guinea',
    awayFlag: require('../testingTipster/images/Guinea.png'),
    round: 2,
    date: new Date(2019, 6, 26, 16, 30),
  }, {
    homeTeam: 'Madagascar',
    homeFlag: require('../testingTipster/images/Madagascar.png'),
    awayTeam: 'Burundi',
    awayFlag: require('../testingTipster/images/Burundi.png'),
    round: 2,
    date: new Date(2019, 6, 27, 16, 30),
  }, {
    homeTeam: 'Senegal',
    homeFlag: require('../testingTipster/images/Senegal.png'),
    awayTeam: 'Algeria',
    awayFlag: require('../testingTipster/images/Algeria.png'),
    round: 2,
    date: new Date(2019, 6, 27, 19, 0),
  }, {
    homeTeam: 'Kenya',
    homeFlag: require('../testingTipster/images/Kenya.png'),
    awayTeam: 'Tanzania',
    awayFlag: require('../testingTipster/images/Tanzania.png'),
    round: 2,
    date: new Date(2019, 6, 27, 22, 0),
  }, {
    homeTeam: 'Morocco',
    homeFlag: require('../testingTipster/images/Morocco.png'),
    awayTeam: 'Ivory Coast',
    awayFlag: require('../testingTipster/images/Ivory Coast.png'),
    round: 2,
    date: new Date(2019, 6, 28, 19, 0),
  }, {
    homeTeam: 'South Africa',
    homeFlag: require('../testingTipster/images/South Africa.png'),
    awayTeam: 'Namibia',
    awayFlag: require('../testingTipster/images/Namibia.png'),
    round: 2,
    date: new Date(2019, 6, 28, 22, 0),
  }, {
    homeTeam: 'Tunisia',
    homeFlag: require('../testingTipster/images/Tunisia.png'),
    awayTeam: 'Mali',
    awayFlag: require('../testingTipster/images/Mali.png'),
    round: 2,
    date: new Date(2019, 6, 28, 16, 30),
  }, {
    homeTeam: 'Mauritius',
    homeFlag: require('../testingTipster/images/Mauritius.png'),
    awayTeam: 'Angola',
    awayFlag: require('../testingTipster/images/Angola.png'),
    round: 2,
    date: new Date(2019, 6, 29, 16, 30),
  }, {
    homeTeam: 'Cameroon',
    homeFlag: require('../testingTipster/images/Cameroon.png'),
    awayTeam: 'Ghana',
    awayFlag: require('../testingTipster/images/Ghana.png'),
    round: 2,
    date: new Date(2019, 6, 29, 19, 0),
  }, {
    homeTeam: 'Benin',
    homeFlag: require('../testingTipster/images/Benin.png'),
    awayTeam: 'Guinea-Bissau',
    awayFlag: require('../testingTipster/images/Guinea-Bissau.png'),
    round: 2,
    date: new Date(2019, 6, 29, 22, 0),
  }, {
    homeTeam: 'Uganda',
    homeFlag: require('../testingTipster/images/Uganda.png'),
    awayTeam: 'Egypt',
    awayFlag: require('../testingTipster/images/Egypt.png'),
    round: 3,
    date: new Date(2019, 6, 30, 21, 0),
  }, {
    homeTeam: 'Zimbabwe',
    homeFlag: require('../testingTipster/images/Zimbabwe.png'),
    awayTeam: 'DR Congo',
    awayFlag: require('../testingTipster/images/DR Congo.png'),
    round: 3,
    date: new Date(2019, 6, 30, 21, 0),
  }, {
    homeTeam: 'Madagascar',
    homeFlag: require('../testingTipster/images/Madagascar.png'),
    awayTeam: 'Nigeria',
    awayFlag: require('../testingTipster/images/Nigeria.png'),
    round: 3,
    date: new Date(2019, 6, 30, 18, 0),
  }, {
    homeTeam: 'Burundi',
    homeFlag: require('../testingTipster/images/Burundi.png'),
    awayTeam: 'Guinea',
    awayFlag: require('../testingTipster/images/Guinea.png'),
    round: 3,
    date: new Date(2019, 6, 30, 18, 0),
  }, {
    homeTeam: 'Kenya',
    homeFlag: require('../testingTipster/images/Kenya.png'),
    awayTeam: 'Senegal',
    awayFlag: require('../testingTipster/images/Senegal.png'),
    round: 3,
    date: new Date(2019, 7, 1, 21, 0),
  }, {
    homeTeam: 'Tanzania',
    homeFlag: require('../testingTipster/images/Tanzania.png'),
    awayTeam: 'Algeria',
    awayFlag: require('../testingTipster/images/Algeria.png'),
    round: 3,
    date: new Date(2019, 7, 1, 21, 0),
  }, {
    homeTeam: 'South Africa',
    homeFlag: require('../testingTipster/images/South Africa.png'),
    awayTeam: 'Morocco',
    awayFlag: require('../testingTipster/images/Morocco.png'),
    round: 3,
    date: new Date(2019, 7, 1, 18, 0),
  }, {
    homeTeam: 'Namibia',
    homeFlag: require('../testingTipster/images/Namibia.png'),
    awayTeam: 'Ivory Coast',
    awayFlag: require('../testingTipster/images/Ivory Coast.png'),
    round: 3,
    date: new Date(2019, 7, 1, 18, 0),
  }, {
    homeTeam: 'Mauritius',
    homeFlag: require('../testingTipster/images/Mauritius.png'),
    awayTeam: 'Tunisia',
    awayFlag: require('../testingTipster/images/Tunisia.png'),
    round: 3,
    date: new Date(2019, 7, 2, 21, 0),
  }, {
    homeTeam: 'Angola',
    homeFlag: require('../testingTipster/images/Angola.png'),
    awayTeam: 'Mali',
    awayFlag: require('../testingTipster/images/Mali.png'),
    round: 3,
    date: new Date(2019, 7, 2, 21, 0),
  }, {
    homeTeam: 'Benin',
    homeFlag: require('../testingTipster/images/Benin.png'),
    awayTeam: 'Cameroon',
    awayFlag: require('../testingTipster/images/Cameroon.png'),
    round: 3,
    date: new Date(2019, 7, 2, 18, 0),
  }, {
    homeTeam: 'Guinea-Bissau',
    homeFlag: require('../testingTipster/images/Guinea-Bissau.png'),
    awayTeam: 'Ghana',
    awayFlag: require('../testingTipster/images/Ghana.png'),
    round: 3,
    date: new Date(2019, 7, 2, 18, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 4,
    date: new Date(2019, 7, 5, 18, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 4,
    date: new Date(2019, 7, 5, 21, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 4,
    date: new Date(2019, 7, 6, 18, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 4,
    date: new Date(2019, 7, 6, 21, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 4,
    date: new Date(2019, 7, 7, 18, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 4,
    date: new Date(2019, 7, 7, 21, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 4,
    date: new Date(2019, 7, 8, 18, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 4,
    date: new Date(2019, 7, 8, 21, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 5,
    date: new Date(2019, 7, 10, 18, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 5,
    date: new Date(2019, 7, 10, 21, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 5,
    date: new Date(2019, 7, 11, 18, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 5,
    date: new Date(2019, 7, 11, 21, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 6,
    date: new Date(2019, 7, 14, 18, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 6,
    date: new Date(2019, 7, 14, 21, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 7,
    date: new Date(2019, 7, 17, 21, 0),
  }, {
    homeTeam: '---',
    homeFlag: require('../testingTipster/images/---.png'),
    awayTeam: '---',
    awayFlag: require('../testingTipster/images/---.png'),
    round: 7,
    date: new Date(2019, 7, 19, 21, 0),
  },
];
export default matches;
